// Unit Include
#include "c-link.h"

// Qx Includes
#include <qx/linux/qx-applicationdesktopentry.h>

// Project Includes
#include "c-play.h"
#include "utility.h"

//===============================================================================================================
// CSHORTCUT
//===============================================================================================================

//-Instance Functions-------------------------------------------------------------
//Private:
Qx::Error CLink::createShortcut(const QString& name, const QDir& dir, QUuid id)
{
    // Add/update CLIFp icon set
    if(!Utility::installAppIconForUser())
    {
        CLinkError err(CLinkError::IconInstallFailed);
        mCore.postError(NAME, err);
        return err;
    }

    // Setup desktop entry
    Qx::ApplicationDesktopEntry ade;
    ade.setName(name);
    ade.setIcon(PROJECT_SHORT_NAME);
    QString args = CPlay::NAME + u" -"_s + TitleCommand::CL_OPTION_ID.names().constFirst() + ' ' + id.toString(QUuid::WithoutBraces);
    ade.setExec(CLIFP_DIR_PATH + '/' + CLIFP_CUR_APP_FILENAME + ' ' + args);
    ade.setPath(CLIFP_DIR_PATH);
    ade.setComment(u"Generated by "_s PROJECT_SHORT_NAME " " PROJECT_VERSION_STR);

    // Create entry
    QString filename = u"org.flashpoint.clifp."_s + id.toString(QUuid::WithoutBraces) +
                       '.' + shortcutExtension();
    QString fullEntryPath = dir.absoluteFilePath(filename);
    Qx::IoOpReport writeReport = Qx::DesktopEntry::writeToDisk(fullEntryPath, &ade);

    // Check for write error
    if(writeReport.isFailure())
    {
        mCore.postError(NAME, writeReport);
        return writeReport;
    }

    mCore.logEvent(NAME, LOG_EVENT_CREATED_SHORTCUT.arg(id.toString(QUuid::WithoutBraces), QDir::toNativeSeparators(fullEntryPath)));

    // Return success
    return CLinkError();
}

QString CLink::shortcutExtension() const { return u"desktop"_s; };
