name: Build CLIFp - Linux
on:
  workflow_call:
    secrets:
      qt_ffynnon_cred:
        description: 'Credentials for getting Qt from Ffynnon'
        required: true
env:
  qt_install_dir: ${{ github.workspace }}/Qt/Install
  clifp_src_suffix: CLIFp/Source
  clifp_src_dir: ${{ github.workspace }}/CLIFp/Source
  clifp_build_dir: ${{ github.workspace }}/CLIFp/Build

jobs:
  build-clifp:
    name: Build CLIFp - Linux (Release)
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        compiler: [{c: gcc-12, cxx: g++-12, qt: clang14}, {c: clang-12, cxx: clang++-12, qt: clang12}, {c: clang-14, cxx: clang++-14, qt: clang14}]
        linkage: [{type: shared, cmake_bsl: ON}, {type: static, cmake_bsl: OFF}]
        exclude:
            - os: ubuntu-20.04
              compiler: {c: gcc-12, cxx: g++-12, qt: clang14}
            - os: ubuntu-20.04
              compiler: {c: clang-14, cxx: clang++-14, qt: clang14}
            - os: ubuntu-22.04
              compiler: {c: clang-12, cxx: clang++-12, qt: clang12}
    runs-on: ${{ matrix.os }}
    env:
      cmake_gen: Ninja Multi-Config
    steps:
    - name: Set derived variables with shell because GitHub Actions env context sucks
      run: |  
        echo "clifp_package_path=${{ env.clifp_build_dir }}/out/dist" >> $GITHUB_ENV
        clifp_install_path="${{ env.clifp_build_dir }}/out/install"
        echo "clifp_install_path=$clifp_install_path" >> $GITHUB_ENV
        echo "qt_cmake=$qt_install_dir/bin/qt-cmake" >> $GITHUB_ENV
    - name: Install Qt (custom build)
      uses: oblivioncth/actions/general/install-and-cache-qt-from-ffynnon@dev
      with:
        version: 6.6.0
        os: linux
        compiler: ${{ matrix.compiler.qt }}
        linkage: ${{ matrix.linkage.type }}
        path: ${{ env.qt_install_dir }}
        credentials: ${{ secrets.qt_ffynnon_cred }}
    - name: Update package index
      run: sudo apt-get update
    - name: Install OpenGL lib
      run: sudo apt-get install libglu1-mesa-dev
    - name: Install XCB Related libs
      run: sudo apt-get install libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev libxcb-*-dev
    - name: Install libdrm
      run: sudo apt-get install libdrm-dev
    - name: Install Ninja
      run: sudo apt-get install ninja-build
    - name: Install Harfbuzz
      run: sudo apt-get install libharfbuzz-dev
    - name: Install EGL [22.04]
      if: matrix.os == 'ubuntu-22.04'
      run: sudo apt-get install libegl1-mesa-dev
    - name: Install Wayland
      run: sudo apt-get install libwayland-dev
    - name: Checkout CLIFp
      uses: actions/checkout@v4
      with:
        path: ${{ env.clifp_src_suffix }}
        fetch-depth: 0 # Required for verbose versioning to work correctly
    - name: Build/Install CLIFp
      working-directory: ${{ env.clifp_src_dir }}
      run: |
        echo Configuring CMake...
        "$qt_cmake" -G "$cmake_gen" -S "$clifp_src_dir" -B "$clifp_build_dir" -D BUILD_SHARED_LIBS="${{ matrix.linkage.cmake_bsl }}" -D CMAKE_CXX_COMPILER="${{ matrix.compiler.cxx }}" -D CMAKE_C_COMPILER="${{ matrix.compiler.c }}"
        echo Changing to build directory...
        cd "$clifp_build_dir"
        echo Building CLIFp Release...
        cmake --build . --target all --config Release
        echo Installing CLIFp Release
        cmake --install . --config Release
        echo Packaging CLIFp...
        cpack -C "Release"
        echo Build complete.
    - name: Get CLIFp artifact name
      run: |
        cpack_name=$(find "${{ env.clifp_package_path }}" -type f -name "*.zip")
        artifact_name="$(basename "$cpack_name" .zip) [${{ matrix.compiler.cxx }}]"
        echo "current_artifact_name=$artifact_name" >> $GITHUB_ENV
    - name: Upload CLIFp build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.current_artifact_name }}
        path: ${{ env.clifp_install_path }}
        if-no-files-found: error
