name: Build CLIFp - Linux
on:
  workflow_call:
    secrets:
      qt_ffynnon_cred:
        description: 'Credentials for getting Qt from Ffynnon'
        required: true
    outputs:
      qt_static_artifact_name:
        description: "CLIFp (Qt static) build artifact"
        value: ${{ jobs.build-clifp.outputs.qt_static_artifact_name }}
env:
  general_download_dir: ${{ github.workspace }}/Download
  qt_install_dir: ${{ github.workspace }}/Qt/Install
  clifp_src_suffix: CLIFp/Source
  clifp_src_dir: ${{ github.workspace }}/CLIFp/Source
  clifp_build_dir: ${{ github.workspace }}/CLIFp/Build

jobs:
  build-clifp:
    name: Build CLIFp - Linux (Release)
    strategy:
      matrix:
        qt_linkage: [static]
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    env:
      c_comp: clang-12
      cxx_comp: clang++-12
      cmake_gen: Ninja Multi-Config
    outputs:
      qt_static_artifact_name: ${{ steps.get_artifact_name.outputs.qt_static_artifact_name }}
    steps:
    - name: Set derived variables with shell because GitHub Actions env context sucks
      run: |  
        echo "clifp_package_path=${{ env.clifp_build_dir }}/out/dist" >> $GITHUB_ENV
        clifp_install_path="${{ env.clifp_build_dir }}/out/install"
        echo "clifp_install_path=$clifp_install_path" >> $GITHUB_ENV
        echo "qt_cmake=$qt_install_dir/bin/qt-cmake" >> $GITHUB_ENV
    - name: Install Qt (custom build)
      uses: oblivioncth/actions/general/install-and-cache-qt-from-ffynnon@dev
      with:
        version: 6.4.0
        os: linux
        compiler: clang
        linkage: ${{ matrix.qt_linkage }}
        path: ${{ env.qt_install_dir }}
        credentials: ${{ secrets.qt_ffynnon_cred }}    
    - name: Install OpenGL lib
      run: sudo apt-get install libglu1-mesa-dev
    - name: Install XCB Related libs
      run: sudo apt-get install libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev libxcb-*-dev
    - name: Install libdrm
      run: sudo apt-get install libdrm-dev
    - name: Install Ninja
      run: sudo apt-get install ninja-build
    - name: Install Harfbuzz
      run: sudo apt-get install libharfbuzz-dev
    - name: Checkout CLIFp
      uses: actions/checkout@v3
      with:
        path: ${{ env.clifp_src_suffix }}
        fetch-depth: 0 # Required for verbose versioning to work correctly
    - name: Build/Install CLIFp
      working-directory: ${{ env.clifp_src_dir }}
      run: |
        echo Configuring CMake...
        "$qt_cmake" -G "$cmake_gen" -S "$clifp_src_dir" -B "$clifp_build_dir" -D CMAKE_CXX_COMPILER="$cxx_comp" -D CMAKE_C_COMPILER="$c_comp"
        echo Changing to build directory...
        cd "$clifp_build_dir"
        echo Building CLIFp Release...
        cmake --build . --target all --config Release
        echo Installing CLIFp Release
        cmake --build . --target install --config Release
        echo Packaging CLIFp...
        cpack -C "Debug;Release"
        echo Build complete.
    - name: Get CLIFp artifact name
      id: get_artifact_name
      run: |
        cpack_name=$(find "${{ env.clifp_package_path }}" -type f -name "*.zip")
        artifact_name="$(basename "$cpack_name" .zip) [${{ matrix.os }}]"
        echo "clifp_current_artifact_name=$artifact_name" >> $GITHUB_ENV
        echo "qt_${{ matrix.qt_linkage }}_artifact_name=$artifact_name" >> $GITHUB_OUTPUT
    - name: Upload CLIFp build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.clifp_current_artifact_name }}
        path: ${{ env.clifp_install_path }}
        if-no-files-found: error
