name: Build CLIFp - Windows (Qt 6.3.0)
on:
  workflow_call:
    secrets:
      qt_static_dec_key:
        description: 'MEGA decryption key for Qt static install archive URL'
        required: true
    outputs:
      qt_static_artifact_name:
        description: "CLIFp (Qt static) build artifact"
        value: ${{ jobs.build-clifp.outputs.qt_static_artifact_name }}
env:
  qt_install_dir: ${{ github.workspace }}/Qt/Install
  qt_download_dir: ${{ github.workspace }}/Qt/Download
  clifp_src_suffix: CLIFp/Source
  clifp_src_dir: ${{ github.workspace }}/CLIFp/Source
  clifp_build_dir: ${{ github.workspace }}/CLIFp/Build

jobs:
  build-clifp:
    name: Build CLIFp - Windows (Release)
    strategy:
      matrix:
        qt_linkage: [static]
    runs-on: windows-latest
    env:
      vs_dev_dir: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/Tools
      cmake_gen: Ninja Multi-Config
    outputs:
      qt_shared_artifact_name: ${{ steps.get_artifact_name.outputs.qt_shared_artifact_name }}
      qt_static_artifact_name: ${{ steps.get_artifact_name.outputs.qt_static_artifact_name }}
    steps:
    - name: Set matrix derived variables
      uses: kanga333/variable-mapper@v0.2.2
      with:
        key: ${{ matrix.qt_linkage }}
        map: |
          {
            "static": {
              "qt_install_name": "qt-Production-6.3.0-win32-msvc-x64-static-release.7z",
              "qt_install_url": "https://mega.nz/file/J7IxAbYL",
              "qt_install_url_key": "${{ secrets.qt_static_dec_key }}",
              "artifact_output_var": "qt_static_artifact_name"
            }
          }
        export_to: env,log
    - name: Set derived variables with shell because GitHub Actions env context sucks
      run: |
        echo "qt_install_dest=${{ env.qt_download_dir }}/${{ env.qt_install_name }}" >> $Env:GITHUB_ENV
        echo "clifp_package_path=${{ env.clifp_src_dir }}/out/dist" >> $Env:GITHUB_ENV
        $clifp_install_path="${{ env.clifp_src_dir }}/out/install"
        echo "clifp_install_path=$clifp_install_path" >> $Env:GITHUB_ENV
        echo "qt_cmake=${Env:qt_install_dir}/bin/qt-cmake.bat" >> $Env:GITHUB_ENV
    - name: Cache Qt Build
      id: cache-qt
      uses: actions/cache@v3
      with:
        path: ${{ env.qt_install_dir }}
        key: ${{ env.qt_install_name }}
    - name: Install megatools
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: choco install megatools
    - name: Create Qt Download Directory
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: New-Item -Path "${{ env.qt_download_dir }}" -ItemType "directory"
    - name: Download Qt Install
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: megatools dl "${Env:qt_install_url}#${Env:qt_install_url_key}" --path "${{ env.qt_download_dir }}"
    - name: Extract Qt Install
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: 7z x ${{ env.qt_install_dest }} -o${{ env.qt_install_dir }}
    - name: Checkout CLIFp
      uses: actions/checkout@v3
      with:
        path: ${{ env.clifp_src_suffix }}
        fetch-depth: 0 # Required for verbose versioning to work correctly
    - name: Build/Install CLIFp
      working-directory: ${{ env.clifp_src_dir }}
      run: |
        Write-Host "Loading VS Command Prompt Environment..." -ForegroundColor Green
        if (!(Test-Path -Path "${Env:vs_dev_dir}/VsDevCmd.bat" -PathType Leaf)) {
          throw "VsDevCmd.bat was not found in $VsDevCmdDir"
        }
        pushd "$Env:vs_dev_dir"
        cmd /c "VsDevCmd.bat -arch=amd64 & set" |
        foreach {
          if ($_ -match "=") {
          $v = $_.split("=", 2); set-item -force -path "ENV:\$($v[0])"  -value "$($v[1])" 
          }
        }
        popd
        Write-Host "Building CLIFp..." -ForegroundColor Green
        echo "Configuring CMake..."
        Start-Process -FilePath "${{ env.qt_cmake }}" -ArgumentList '-G "${{ env.cmake_gen }}" -S "${{ env.clifp_src_dir}}" -B "${{ env.clifp_build_dir }}"' -Wait -NoNewWindow
        echo "Changing to build directory..."
        cd "$Env:clifp_build_dir"
        echo "Building CLIFp release..."
        cmake --build . --target all --config Release
        echo "Installing CLIFp Release..."
        cmake --build . --target install --config Release
        echo "Packaging CLIFp..."
        cpack -C "Release"
        echo "Build complete."
    - name: Get CLIFp artifact name
      id: get_artifact_name
      run: echo "::set-output name=${{ env.artifact_output_var }}::$((Get-ChildItem -Path "${{ env.clifp_package_path }}" -Filter *.zip)[0].BaseName)"
    - name: Upload CLIFp build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.get_artifact_name.outputs[env.artifact_output_var] }}
        path: ${{ env.clifp_install_path }}
        if-no-files-found: error
