name: Label PR
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    
jobs:
  label-pr:
    name: Label pull-request
    permissions:
      contents: read
      pull-requests: write
    uses: oblivioncth/actions/.github/workflows/label-pr.yml@v1
