name: Pull-request auto-labeler
on:
  pull_request:
    types: [opened]
    
jobs:
  label_master_pr:
    name: Label master pull-request
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Create label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: release-pr
  label_other_pr:
    name: Label other standard pull-requests
    if: github.ref_name != 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Label bugfix PR
        if: startsWith(github.head_ref, 'refs/heads/bugfix/')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: bug
      - name: Label feature PR
        if:  startsWith(github.head_ref, 'refs/heads/feature/')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: enhancement
    