name: CLIFp Push Reaction
on:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'master'

jobs:
  trigger-windows-build:
    name: Build CLIFp (Windows)
    uses: ./.github/workflows/build-clifp-windows.yml
    secrets:
      qt_ffynnon_cred: ${{ secrets.OBYBOT_FFYNNON_CREDS }}
      
  trigger-linux-build:
    name: Build CLIFp (Linux)
    uses: ./.github/workflows/build-clifp-linux.yml
    secrets:
      qt_ffynnon_cred: ${{ secrets.OBYBOT_FFYNNON_CREDS }}